# Generated by Django 5.2 on 2025-04-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
